#!/bin/bash

docker buildx create --name multiarch --bootstrap --use
docker buildx ls
docker buildx build --platform linux/amd64,linux/arm64 --build-arg SERVER_USERNAME=$SERVER_USERNAME --build-arg SERVER_PASSWORD=$SERVER_PASSWORD -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
